version: '3'

services:
  react-app:
    build: .
    entrypoint: sleep infinity
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
    restart: always

  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - react-app
  #   restart: always
